### ISSUE TITLE
P203171 obverse line 5 Blank translation lines

### ISSUE THREAD

**Issue by rillian** [cdli-gh/data#11]
In [P203171](https://cdli.ucla.edu/P203171) obverse line 5 and reverse line 1, the second empty translation lines should probably be removed.
```
5. ki-es3-sa2{ki#} 
#tr.en: Ki’eša, 
#tr.en: 
@reverse 
1. e2 dingir-re-ne#
#tr.en: houses of the gods, 
#tr.en: 
```

**Comment by epageperron** [comment]
corrected !
