### ISSUE TITLE
Catalogue data for P277115 and P277116 run together

### ISSUE THREAD

**Issue by rillian** [cdli-gh/data#15]
There seems to be some corruption in the catalogue data export for [P277115 and P277116](https://cdli.ucla.edu/search/search_results.php?SearchMode=Text&ObjectID=P277115,P277116). On line 124209 of `cdli_catalogue_1of2.csv`, the **sub-genre comments** column of the first tablet stops abruptly, without a closing quotation mark, and is followed by the entry for the second tablet on the same line.

```csv
[...],"Account; payments of shekel of ?; 10x16x2(u.e.)x2(le.e.,,,,21198/zz001w65nd,"no atf",[..]
```

**Comment by rillian** [comment]
The [archive page](https://cdli.ucla.edu/search/archival_view.php?ObjectID=P277115) for P277115 (N  2004) has slightly more data in this column, but still looks a little strange.

    Account; payments of shekel of ?; 10x16x2(u.e.)x2(le.e. lines

Maybe there's a special character in the database which is causing escaping problems with the export?

**Comment by epageperron** [comment]
Merged #18  in
@rillian  you're not alone :) I'll try to fix this ASAP

**Comment by epageperron** [comment]
I've updated the entry, updated cat my MySQL, runt he export script and the commit script. Please try again anytime. @rillian, @jnovotny-lmu

**Comment by rillian** [comment]
Confirmed fixed. Thanks!
