### ISSUE TITLE
P464358 malformed translation directives

### ISSUE THREAD

**Issue by rillian** [cdli-gh/data#19]
In [P464358](https://cdli.ucla.edu/P464358) law 16 line 527, there's a space between the translation directive and the language code. `#tr. en` should be `#tr.en`. On lines 529 and 530, `#tr.tr` should be `#tr.ts`.
```
@law 16
[...]
527. la usz-te-s,i2-a-am
#tr.ts: lā uštēṣiam
#tr. en: has not let him go out,
[...]
529. id-da-ak          
#tr.tr: iddâk             
#tr.en: shall be killed.
@law 17
530. szum-ma a-wi-lum
#tr.tr: šumma awīlum
#tr.en: If a man
```

**Comment by epageperron** [comment]
corrected, thanks!
