### ISSUE TITLE
P100643 invalid markup

### ISSUE THREAD

**Issue by rillian** [cdli-gh/data#26]
In [P100643](https://cdli.ucla.edu/P100643) the `& blank space` state markup should be `$ blank space` (wrong sigil) and the previous line should probably be labelled `2` instead of the duplicate `3`.

```
@reverse        
1. ur-ba-gara2      
3. szu ba-ti 
& blank space           
3. mu us2-sa an-sza-an{ki} ba-hul
```

**Comment by epageperron** [comment]
corrected

**Comment by rillian** [comment]
thanks!
