### ISSUE TITLE
P125779 duplicate indication

### ISSUE THREAD

**Issue by rillian** [cdli-gh/data#27]
[P125779](https://cdli.ucla.edu/P125779) is marked as a duplicate/copy of [P126262](https://cdli.ucla.edu/P126262). I'm not sure what the correct syntax for this is, but using a `&`-line probably isn't it and confuses parsers.

```
&P125779 = PDT 1, 0363
& (obverse & obverse copy of P126262 = PDT 2, 0902)
```

Perhaps it should be a `$`-line, `>>`, or comment instead? Also it's not clear what `obverse & obverse` refers to. Should that be `obverse & reverse`?

**Comment by rillian** [comment]
[P141740](https://cdli.ucla.edu/P141740) has the same problem.

```
&P141740 = UTI 6, 3743
#atf: lang sux 
@tablet 
& (obverse & obverse copy of P126262 = PDT 2, 0902)
```

**Comment by epageperron** [comment]
@khoidt

**Comment by epageperron** [comment]
corrected
