### ISSUE TITLE
Instead of @column, some objects have @columnn (two n)

### ISSUE THREAD

**Issue by ACL90** [cdli-gh/data#50]
In cdliatf_unblocked.atf :

1 | BRM 3, 031 | @columnn 1
2 | BRM 3, 031 | @columnn 2
3 | BRM 3, 050 | @columnn 1
4 | BRM 3, 050 | @columnn 2
5 | CST 696 | @columnn 1
6 | CST 696 | @columnn 2
7 | PDT 1, 0377 | @columnn 1
8 | PDT 1, 0377 | @columnn 2
9 | PDT 1, 0388 | @columnn 1
10 | PDT 1, 0388 | @columnn 2
11 | PDT 1, 0396 | @columnn 1
12 | PDT 1, 0396 | @columnn 2
13 | PDT 1, 0398 | @columnn 1
14 | PDT 1, 0398 | @columnn 2
15 | PDT 1, 0482 | @columnn 1
16 | PDT 1, 0483 | @columnn 1
17 | PDT 1, 0483 | @columnn 2
18 | PDT 1, 0488 | @columnn 1
19 | PDT 1, 0488 | @columnn 2
20 | PDT 1, 0498 | @columnn 1
21 | PDT 1, 0498 | @columnn 2
22 | PDT 1, 0522 | @columnn 1
23 | PDT 1, 0522 | @columnn 2
24 | PDT 1, 0528 | @columnn 1
25 | PDT 1, 0528 | @columnn 2
26 | PDT 1, 0538 | @columnn 1
27 | PDT 1, 0538 | @columnn 2
28 | PDT 1, 0569 | @columnn 1
29 | PDT 1, 0569 | @columnn 2
30 | PDT 1, 0586 | @columnn 1
31 | PDT 1, 0586 | @columnn 2
32 | PDT 1, 0587 | @columnn 1
33 | PDT 1, 0587 | @columnn 2
34 | PDT 1, 0609 | @columnn 1
35 | PDT 1, 0609 | @columnn 2
36 | PDT 1, 0610 | @columnn 1
37 | PDT 1, 0610 | @columnn 2
38 | PDT 1, 0682 | @columnn 1
39 | PDT 1, 0682 | @columnn 2
40 | SAT 3, 1359 | @columnn 1
41 | SAT 3, 1359 | @columnn 2
42 | CBS 09275 | @columnn 1
43 | RIME 1.14.20.01, ex. 63 | @columnn 1
44 | RIME 2.13.01.01b | @columnn 1
45 | RIME 2.13.01.01b | @columnn 2
46 | RIME 4.01.05.04, ex. add120 | @columnn 1
47 | RIME 4.01.05.04, ex. add120 | @columnn 2
48 | RINAP 3/1 Sennacherib 24 composite | @columnn 1
49 | RIME 3/1.01.07.041, ex. add403 | @columnn 1
50 | ARTA 2015/003 | @columnn 1
51 | ARTA 2015/003 | @columnn 2
52 | CTMMA 1, 002 | @columnn 1
53 | CTMMA 1, 002 | @columnn 2
54 | TSÅ  0936 | @columnn 1
55 | TSÅ  0936 | @columnn 2
56 | MARI 05, p. 071, 104-105 no. 06 | @columnn 1
57 | MARI 05, p. 071, 104-105 no. 06 | @columnn 2

-----
By the way, thanks for the amazing work!

**Comment by ACL90** [comment]
Similarly:
@columm 2      @coulmn 1       @envlope                @reveres      @surfacs a

**Comment by Bertlaf** [comment]
Above references fixed. Please give complete references with "@columm 2 @coulmn 1 @envlope @Reveres @surfacs a"

**Comment by epageperron** [comment]
searching for /columm/ in "structure" field of advanced search gives me P394485, I think this can be done for all those structure keywords. (I fixed P394485)

**Comment by epageperron** [comment]
I searched directly in mysql and found them, then corrected. I guess advanced search cannot handle that level of structure search.. thanks !
