### ISSUE TITLE
spelling mistakes in translation_source (very low importance)

### ISSUE THREAD

**Issue by ACL90** [cdli-gh/data#51]
File cdli_catalogue_xof2:
in translation_source, there are notably:
check
no tranlsation ..71 cases
no translation 
no translation (witness)

The second one seems to be a spelling mistake.

**Comment by epageperron** [comment]
@bertlaf I searched for "no tranlasation" in the translation_source field on file maker and updated the record with proper content for the field with the replace field content function

**Comment by Bertlaf** [comment]
#51: @columm @coulmn @envlope are corrected, but I could not find any @Reveres nor @surfacs
Can #51 be closed?

Le 3 oct. 2019 à 15:43, Émilie Pagé-Perron <notifications@github.com<mailto:notifications@github.com>> a écrit :


@Bertlaf<https://github.com/Bertlaf> I searched for "no tranlasation" in the translation_source field on file maker and updated the record with proper content for the field with the replace field content function
