### ISSUE TITLE
possible to have a "?" or "a" or "b" after @column

### ISSUE THREAD

**Issue by ACL90** [cdli-gh/data#53]
It is the case in the following objects:

@column 2'?   	// STTI 2 p. 075 Ist L 09377
@column 7?	//YOS 15, 115
@column 1?	//CUSAS 03, 0984
@column 2?	//CUSAS 03, 0984
@column 3?	//CUSAS 03, 0984
@column 1a	//CUSAS 26, 045
@column 1b	//CUSAS 26, 045
@column 2'?	//CDLI Literary 000343, ex. 037
@column 1'?	//CDLI Literary 000343, ex. 037

**Comment by epageperron** [comment]
a or b are fine but not ?

**Comment by epageperron** [comment]
@khoidt its easier to work with P number for us if its possible for you to give those refs instead of prim pub?

**Comment by ACL90** [comment]
@column 2'? 
@column 1'? 
&P346461 = CDLI Literary 000343, ex. 037

@column 7? 
&P414524 = YOS 15, 115 

@column 1?
&P332865 = MHET 1/2, 023 
&P499906 = CUSAS 03, 0984 

@column 2? 
@column 3? 
&P499906 = CUSAS 03, 0984
