### ISSUE TITLE
Museum number "BM — PJ" → "BM —"

### ISSUE THREAD

**Issue by rillian** [cdli-gh/data#59]
In 0dcae76cebcd5f19a7b1b0d5d87fc356a865a450 (2020 January 8) the Museum No. field in the exported catalogue changed from `BM — PJ` to just `BM —` on every tablet with that designation. Was this intentional?

**Comment by epageperron** [comment]
It most certainly was but I cannot trace the change since it will have been done in Filemaker...

**Comment by rillian** [comment]
Ok. I was using this to select a subset of tablets with clean atf for the cdli-cts converter. I'll pick something else.

Thanks for checking!

**Comment by epageperron** [comment]
The only reliable id is the P number and unfortunately they do change sometimes but only in exceptional circumstances (eg a duplicate entry is found).
