### ISSUE TITLE
P127683 has invalid cdli number

### ISSUE THREAD

**Issue by rillian** [cdli-gh/data#7]
[P127683](https://cdli.ucla.edu/P127683) is listed without a P-number. The record begins with `&1` instead of  `&P127683`
```
13. u4 2(u) 6(disz)-kam 
14. iti ezem-{d}li9-si4? 
&1 = RA 019, 040 21 
#atf: lang sux 
@tablet 
@obverse 
1. [...] x x x x 
```

It looks like this was [introduced inadvertently](https://cdli.ucla.edu/search/revhistory.php/?txtpnumber=127683) a 2015 June 24 edit.

**Comment by epageperron** [comment]
Corrected.
